trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: 'pull'
    container: 'anithaarun/robotframework-apexon:latest'
  displayName: 'Pull Docker Image from Docker Hub'

- script: |
    docker build -t my-custom-image:latest .
  displayName: 'Build Docker Image'
