trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker pull anithaarun/robotframework-apexon:latest
  displayName: 'Pull Docker Image from Docker Hub'

- script: |
    docker build -t my-custom-image:latest .
  displayName: 'Build Docker Image'
