trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Building Docker image..."
    docker build -t my-custom-image:latest .
  displayName: 'Build Docker Image'

- script: |
    echo "Running Docker container with host network..."
    docker run --name my-container --network host -d my-custom-image:latest /bin/bash -c "while true; do sleep 30; done;"
  displayName: 'Run Docker Container'

- script: |
    echo "Checking ADB version and status inside Docker container..."
    docker exec my-container /bin/bash -c "adb --version"
    docker exec my-container /bin/bash -c "adb start-server"
    docker exec my-container /bin/bash -c "adb devices"
  displayName: 'Check ADB Status'

- script: |
    echo "Connecting to Android device via ADB..."
    docker exec my-container /bin/bash -c "adb connect 10.39.8.149:5555 || echo 'ADB failed to connect to the device. Please check the connection and ensure the device is available.'"
  displayName: 'Connect ADB Device'

- script: |
    echo "Checking connected ADB devices..."
    docker exec my-container /bin/bash -c "adb devices"
  displayName: 'Check Connected Devices'
