trigger:
- main  # Adjust the branch name if needed

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self  # Checkout the code from your repository

- script: |
    echo "Building Docker image..."
    docker build -t my-custom-image:latest .
  displayName: 'Build Docker Image'

- script: |
    echo "Listing Docker images..."
    docker images
  displayName: 'List Docker Images'
