trigger:
- main  # Adjust to your branch name if necessary

pool:
  vmImage: 'ubuntu-latest'

steps:
# Check out the code from your GitHub repository
- checkout: self

# Build Docker image
- script: |
    echo "Building Docker image..."
    docker build -t my-custom-image:latest .
  displayName: 'Build Docker Image'

# Run Docker container
- script: |
    echo "Running Docker container..."
    docker run --name my-container -d my-custom-image:latest
  displayName: 'Run Docker Container'

# Copy the PartnerDevices_Automation folder to the Docker container
- script: |
    echo "Copying PartnerDevices_Automation folder to Docker container..."
    docker cp PartnerDevices_Automation my-container:/app/PartnerDevices_Automation
  displayName: 'Copy Folder to Docker Container'

# Create symbolic links inside the Docker container
- script: |
    echo "Creating symbolic links inside Docker container..."
    docker exec my-container /bin/bash -c "ln -sf /app/PartnerDevices_Automation/resources/Page_objects/Voicemail.json /app/PartnerDevices_Automation/resources/Page_objects/voicemail.json \
    && ln -sf /app/PartnerDevices_Automation/resources/Page_objects/Common.json /app/PartnerDevices_Automation/resources/Page_objects/common.json \
    && ln -sf /app/PartnerDevices_Automation/resources/Page_objects/People.json /app/PartnerDevices_Automation/resources/Page_objects/people.json"
  displayName: 'Create Symbolic Links'

# Run Robot Framework tests inside the Docker container
- script: |
    echo "Running Robot Framework tests..."
    docker exec my-container /bin/bash -c "robot -d /results -i 237605 /app/PartnerDevices_Automation/tests_teams_room"
  displayName: 'Run Robot Framework Tests'

# Stop and remove the Docker container
- script: |
    echo "Stopping Docker container..."
    docker stop my-container
    docker rm my-container
  displayName: 'Stop and Remove Docker Container'
