trigger:
- main  # Adjust to your branch name if necessary

pool:
  vmImage: 'ubuntu-latest'  # Use a Microsoft-hosted agent

steps:
- script: |
    echo "Building Docker image..."
    docker build -t my-custom-image:latest .
  displayName: 'Build Docker Image'

- script: |
    echo "Running Docker container with host network..."
    docker run --name my-container --network host -d my-custom-image:latest /bin/bash -c "while true; do sleep 30; done;"
  displayName: 'Run Docker Container'

- script: |
    echo "Connecting to Android device via ADB..."
    docker exec my-container /bin/bash -c "adb start-server"
    docker exec my-container /bin/bash -c "adb connect 10.39.8.149:5555"
    adb_output=$(docker exec my-container /bin/bash -c "adb devices")
    echo "$adb_output"
    if echo "$adb_output" | grep -q '10.39.8.149:5555'; then
      echo "ADB is connected to the device."
    else
      echo "ADB failed to connect to the device. Please check the connection and ensure the device is available."
      exit 1
    fi
  displayName: 'Connect to ADB Device and Verify'

- script: |
    echo "Stopping Docker container..."
    docker stop my-container
    docker rm my-container
  displayName: 'Stop and Remove Docker Container'
