trigger:
- main  # Adjust to your branch name if necessary

pool:
  vmImage: 'ubuntu-latest'  # Use a Microsoft-hosted agent

steps:
- script: |
    echo "Building Docker image..."
    docker build -t my-custom-image:latest .
  displayName: 'Build Docker Image'

- script: |
    echo "Running Docker container with host network..."
    docker run --name my-container --network host -d my-custom-image:latest /bin/bash -c "while true; do sleep 30; done;"
  displayName: 'Run Docker Container'

- script: |
    echo "Testing ADB functionality in Docker container..."
    set -o pipefail
    adb_output=$(docker exec my-container /bin/bash -c "adb start-server && adb devices")
    echo "$adb_output"
    if echo "$adb_output" | grep -q 'List of devices attached'; then
      echo "ADB is working correctly."
    else
      echo "ADB is not working correctly. Please check the ADB setup."
      exit 1
    fi
  displayName: 'Test ADB Functionality'

- script: |
    echo "Stopping Docker container..."
    docker stop my-container
    docker rm my-container
  displayName: 'Stop and Remove Docker Container'
