trigger:
- main  # Adjust to your branch name if necessary

pool:
  name: 'default'  # Specify your self-hosted agent pool here

steps:
- checkout: self

- script: |
    echo "Building Docker image..."
    docker build -t my-custom-image:latest .
  displayName: 'Build Docker Image'

- script: |
    echo "Running Docker container..."
    docker run --name my-container -d my-custom-image:latest /bin/bash -c "while true; do sleep 30; done;"
  displayName: 'Run Docker Container'

- script: |
    echo "Copying PartnerDevices_Automation folder to Docker container..."
    docker cp PartnerDevices_Automation my-container:/app/PartnerDevices_Automation
  displayName: 'Copy Folder to Docker Container'

- powershell: |
    Write-Host "Creating symbolic links inside Docker container..."
    docker exec my-container powershell -Command "cd /app/PartnerDevices_Automation; `
    New-Item -ItemType SymbolicLink -Path resources/Page_objects/voicemail.json -Target resources/Page_objects/Voicemail.json; `
    New-Item -ItemType SymbolicLink -Path resources/Page_objects/common.json -Target resources/Page_objects/Common.json; `
    New-Item -ItemType SymbolicLink -Path resources/Page_objects/people.json -Target resources/Page_objects/People.json"
  displayName: 'Create Symbolic Links'


- script: |
    echo "Running Robot Framework tests..."
    docker exec my-container /bin/bash -c "cd /app/PartnerDevices_Automation && robot -d /results -i 237605 tests_teams_room"
  displayName: 'Run Robot Framework Tests'

- script: |
    echo "Stopping Docker container..."
    docker stop my-container
    docker rm my-container
  displayName: 'Stop and Remove Docker Container'
